### ISSUE TITLE
Category Order does not save

### ISSUE THREAD

**Issue by gitgithubb** [InamuraJIN/ActionRecorder#21] opened 2021-01-21 01:56 UTC
Category Order is not recalled when re-openeing Blender Saved Sessions. Auto save enabled, Save to file "Pressed" prior to saving file, then Quit Blender 2.91-2.92

Within the file directory, Category Order, and Names do reflect the changes made and saved. When re-opening (any) saved Blender file, the Category order is not as saved.. (OSX 10.14).
But upon re-opening the same Blender file, within the File directory, the Category names and order revert back to unsorted.

![1-Category Order upon saving](https://user-images.githubusercontent.com/53125841/105269064-3e4b2700-5b61-11eb-8790-09b60be55892.png)
![2-Category Order reflected in defualt directory](https://user-images.githubusercontent.com/53125841/105269104-4c00ac80-5b61-11eb-95f0-f7f864e5b255.png)
![3-Category Order upon re-opening same doc](https://user-images.githubusercontent.com/53125841/105269117-51f68d80-5b61-11eb-869d-623f333f3989.png)

UPDATE - upon pressing "Save to File", the changes are relcted in the file structure, then, immediately upon pressing "Load from File", the file directory naming reverts back to unsorted.
*pressing "Save to File" then "Load from File" 2 or more times will yeild a different sort order with each time.

https://user-images.githubusercontent.com/53125841/105272907-48bcef00-5b68-11eb-9408-3947cbff544a.mp4

(performed clean install of blender 2.91-2.92, re-installed addon. problem persists) (disk util shows no error on dsk) defualt folder preferences chosen)

Thanks very much. (hope it is on my end, i see no other mentions). cheers to you and yours. be well.

**Comment by RivinHD** [comment] 2021-01-23 16:29
Thank you for your report. I have tried to reproduce the bug, but unfortunately without success.

I'm done some changes and probably find the issue, but I'm not sure because I can't test it.
The issue is probably that the OS system sort the folders differently than windows, but this is fixed in the next update.

If you want to fix it now, you can go to ActionRecorder.py in line 526 (this line of code: `for folder in os.listdir(AR_Var.StorageFilePath):`) and change it with `for folder in sorted(os.listdir(AR_Var.StorageFilePath)):`.

The changes will be in the next update.

**Comment by gitgithubb** [comment] 2021-01-25 15:34
thank you very much for your efforts. so much appreciated. I was not able to verify this on another Mac, so reproducible I could not fully verify. Again thanks much, I understand.  be well. cheers.

**Comment by RivinHD** [comment] 2022-11-24 10:05
Fixed with [Release 4.0.2](https://github.com/InamuraJIN/ActionRecorder/releases/tag/4.0.2)

**Closed by RivinHD** 2022-11-24 10:05 UTC
Labels: bug
